### ISSUE TITLE
服务连续多次调用keybert抽取关键词会报错

### ISSUE THREAD

**Issue by Godlikemandyy** [shibing624/pke_zh#5]
### Describe the bug
使用flask web框架连续多次调用keybert方法抽取文本关键词（上一次调用没有返回结果紧接着进行第二次调用），大概连续连击10次会报2-3次错误，错误如下：
![WechatIMG2273_111](https://github.com/shibing624/pke_zh/assets/36065226/f62bafc3-9ffd-46c6-9d3e-8d753ba0deb4)
为了避免错误，换成了positionrank，就不会出现上述的错误，麻烦帮忙修复一下，多谢！！！

### Context
 - Linux CentOs7
 - python=3.8

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
我用脚本预测keybert，万次并无问题。应该是你起flask服务，没有做输入数据校验，输入有空或者非法字符导致错误。
