### ISSUE TITLE
初始化 wordRank 报错

### ISSUE THREAD

**Issue by yucc-leon** [shibing624/pke_zh#6]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.
想使用wordrank提取关键词，但初始化时报错如下：
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
- 
### To Reproduce
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) here. We hope we can simply copy/paste/run it. It is also nice to share a hosted runnable script (e.g. Google Colab), especially for hardware-related problems.

### Describe your attempts
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: 
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: 
环境：
 -scikit-learn=1.3.1
 -python=3.10

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
你的运行代码是？

**Comment by yucc-leon** [comment]
运行代码
```
from pke_zh.wordrank import WordRank
m = WordRank()
```
运行后先是下载了bert-base权重，加载pickle的时候报错。在ipython模式下完整交互过程如下：
```
from pke_zh.wordrank import WordRank
   ...: m = WordRank()
[2023-11-03 07:07:06,372] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-11-03 07:07:13.148 | DEBUG    | pke_zh.wordrank:__init__:154 - Loaded PMI dict: /cpfs01/shared/public/liyuchen/miniconda3/lib/python3.10/site-packages/pke_zh/data/pmi_word_score.json
2023-11-03 07:07:15.028 | DEBUG    | pke_zh.wordrank:__init__:362 - Loaded language model: /cpfs01/shared/public/liyuchen/.pycorrector/datasets/zh_giga.no_cna_cmn.prune01244.klm.
/cpfs01/shared/public/liyuchen/miniconda3/lib/python3.10/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.0.2 when using version 1.3.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 2
      1 from pke_zh.wordrank import WordRank
----> 2 m = WordRank()

File ~/miniconda3/lib/python3.10/site-packages/pke_zh/wordrank.py:478, in WordRank.__init__(self, model_path, stopwords_path, person_name_path, place_name_path, common_char_path, segment_sep, ngram, pmi_path, entropy_path)
    476     model_path = os.path.join(cache_folder, f'{file_name}')
    477 if model_path and os.path.exists(model_path):
--> 478     self.model = load_pkl(model_path)
    479     logger.debug('Loaded wordrank model: {}'.format(model_path))
    480 self.model_path = model_path

File ~/miniconda3/lib/python3.10/site-packages/pke_zh/utils/io_utils.py:18, in load_pkl(pkl_path)
     12 """
     13 加载词典文件
     14 :param pkl_path:
     15 :return:
     16 """
     17 with open(pkl_path, 'rb') as f:
---> 18     result = pickle.load(f)
     19 return result

File sklearn/tree/_tree.pyx:728, in sklearn.tree._tree.Tree.__setstate__()

File sklearn/tree/_tree.pyx:1432, in sklearn.tree._tree._check_node_ndarray()

ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
```

**Comment by shibing624** [comment]
收到，我看下

**Comment by shibing624** [comment]
1. 安装依赖：networkx<3.0 
2. 更新到pip install pke_zh==0.2.6

**Comment by tomriddle1234** [comment]
仍然不好使，networkx 2.8.8, 2.8.7都试了，不行

**Comment by easily44** [comment]
> 仍然不好使，networkx 2.8.8, 2.8.7都试了，不行

@tomriddle1234 

pip install scikit-learn==1.2.2
